version: "3.9"

services:
  backend:
    build: .
    ports:
      - 4000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/vat/lib/mysql